name: Deploy React App with Terraform + S3 + CloudFront

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    outputs:
      s3_bucket_name: ${{ steps.extract_outputs.outputs.s3_bucket_name }}
      cloudfront_distribution_id: ${{ steps.extract_outputs.outputs.cloudfront_distribution_id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color

      - name: Extract Terraform Outputs
        id: extract_outputs
        run: |
          s3_bucket_name=$(terraform output -raw s3_bucket_name | tr -d '\r\n')
          cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id | tr -d '\r\n')

          echo "s3_bucket_name=$s3_bucket_name"
          echo "cloudfront_distribution_id=$cloudfront_distribution_id"

          echo "::set-output name=s3_bucket_name::$s3_bucket_name"
          echo "::set-output name=cloudfront_distribution_id::$cloudfront_distribution_id"

  deploy:
    name: Build and Deploy React App
    needs: terraform
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      S3_BUCKET_NAME: ${{ needs.terraform.outputs.s3_bucket_name }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ needs.terraform.outputs.cloudfront_distribution_id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./shopping-time
        run: npm install

      - name: Build React app
        working-directory: ./shopping-time
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug Bucket and Distribution ID
        run: |
          echo "S3_BUCKET_NAME: $S3_BUCKET_NAME"
          echo "CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID"

      - name: Sync React App to S3
        run: |
          aws s3 sync shopping-time/dist/ s3://$S3_BUCKET_NAME --delete --acl public-read

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
