name: Deploy React App with Terraform + S3 + CloudFront

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color

      - name: Export Terraform outputs to ENV
        run: |
          echo "Extracting Terraform outputs..."
          S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name | tr -d '\r\n')
          CLOUDFRONT_DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id | tr -d '\r\n')

          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID" >> $GITHUB_ENV

  deploy:
    name: Build and Deploy React App
    needs: terraform
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-south-1
      # These come from the terraform job via GITHUB_ENV
      S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./shopping-time
        run: npm install

      - name: Build React app
        working-directory: ./shopping-time
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug Outputs
        run: |
          echo "Deploying to bucket: $S3_BUCKET_NAME"
          echo "Using distribution: $CLOUDFRONT_DISTRIBUTION_ID"

      - name: Sync React app build to S3
        run: |
          aws s3 sync shopping-time/dist/ s3://$S3_BUCKET_NAME --delete --acl public-read

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
